export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #f7f6fe 0%, #f4fafd 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – ensuring that every practice session feels relevant and personalized. The system adapts to your career level, whether you are a fresher, a student preparing for placements, or a professional aiming for a role switch.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you’re ready. Dive deeper into concepts instantly with AI-powered, detailed explanations that break down complex topics into easy-to-understand insights. Whether you want a quick overview or an in-depth understanding, the system adapts to your learning pace and curiosity.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "“Add personal notes to any question and pin important ones to the top, making your learning more organized and intentional. Capture key insights, mistakes, or strategies as you practice, and quickly revisit high-priority questions whenever needed. This keeps your preparation structured, focused, and easy to revise. ",
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind answers',
    description:
      "Beyond just answers, unlock detailed concept explanations generated by AI, helping you truly master the underlying principles behind each question. This deeper understanding allows you to connect concepts, avoid rote memorization, and confidently apply your knowledge in real interview scenarios and real-world problem solving",
  },
  {
    id: "05",
    title: "Save, Organise, and Revisit",
    description:
      "Easily save your interview sets, organise them neatly in your dashboard, and pick up your preparation right where you left",
  },
];
